# transformer.yaml

data:
    train:
        path_src: tag_tag_src.tok.train.txt
        path_tgt: tag_tgt.tok.train.txt
    valid:
        path_src: tag_tag_src.tok.valid.txt
        path_tgt: tag_tgt.tok.valid.txt

save_data: vocab2
src_vocab: vocab2/vocab.src
tgt_vocab: vocab2/vocab.tgt

save_model: after_transformer


save_checkpoint_steps: 5000
seed: 3435
train_steps: 1000000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
hidden_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 3
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0